/**
 * Base API URL for the application
 */
const BaseURL = "https://www.fldesigners.xyz/"

/**
 * Authentication Token
 * 
 * Generated on user login and stored as a cookie.
 * The token below is a default token generated by an Admin user for development/testing.
 * 
 * @example "10%7CXoIxzHvZv1zkE56iPcqaGCClzlUaFJ6S9G0Kbcu535bf3693"
 */
const authToken = "10%7CXoIxzHvZv1zkE56iPcqaGCClzlUaFJ6S9G0Kbcu535bf3693"

/**
 * Schedule Request Data Structure
 * 
 * @typedef {Object} ScheduleRequestData
 * @property {string} customerName - Customer's full name (from Users table where role = customer)
 * @property {string} customerPhone - Customer's contact phone number
 * @property {string} customerAddress - Customer's physical address
 * @property {string} customerStatus - Current status of the request (e.g., "Requested", "Pending", "Completed")
 * @property {string} requestTime - Time when the request was created (format: HH:MM:SS)
 * @property {string} requestDate - Date when the request was created (format: YYYY-MM-DD)
 * @property {string} centerId - Unique identifier for the assigned recycling center
 * @property {string} centerName - Name of the recycling center
 * @property {string} centerPhone - Contact phone number for the recycling center
 * @property {string} centerAddress - Physical address of the recycling center
 */
const data = {
    customerName: "Enter Customer Name",
    customerPhone: "Enter Customer Phone",
    customerAddress: "Enter Customer Address",
    customerStatus: "Requested",
    requestTime: "Current Time",
    requestDate: "Current Date",
    centerId: "Center Id",
    centerName: "Center Name",
    centerPhone: "Center Phone Number",
    centerAddress: "Center Address"
}

/**
 * Submit a bin collection notification/schedule request
 * 
 * Creates a new schedule entry for customer bin collection by sending customer
 * and recycling center details to the API endpoint.
 * 
 * @param {ScheduleRequestData} data - The schedule request data containing customer and center information
 * @returns {Promise<any>} JSON response from the API containing the created schedule or error details
 * 
 * @example
 * const scheduleData = {
 *   customerName: "John Doe",
 *   customerPhone: "555-0123",
 *   customerAddress: "123 Main St",
 *   customerStatus: "Requested",
 *   requestTime: "14:30:00",
 *   requestDate: "2025-10-22",
 *   centerId: "RC001",
 *   centerName: "Green Recycling Center",
 *   centerPhone: "555-9999",
 *   centerAddress: "456 Industrial Ave"
 * };
 * 
 * const result = await binNotificationSubmit(scheduleData);
 */
export async function binNotificationSubmit(data: any) {
    const res = await fetch(`${BaseURL}api/schedule-of-customer/`, {
        method: 'POST',
        body: JSON.stringify(data),
        headers: {
            'Authorization': `Bearer ${authToken}`,
            'Accept': 'application/json',
            'Content-Type': 'application/json',
        }
    });
    
    return await res.json();
}