export const CenterEntity = {
    id: 0,
    userId: 0,
    name: "",
    phone: "",
    email: "",
    address: "",
    longitude: 0.0,
    latitude: 0.0,
    description: "",
    city: "",
    province: "",
    postalCode: "",
    weekdayOpenTime: "09:00",
    weekdayCloseTime: "00:00",
    weekendOpenTime: "00:00",
    weekendCloseTime: "00:00",
    holidayOpenTime: "00:00",
    holidayCloseTime: "00:00",
    createdAt: "",
    updatedAt: "",
}